name: eduthon
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  pinput: ^5.0.2
  http: ^1.6.0
  iconsax: ^0.0.8
  tflite_flutter: ^0.12.1
  ffi: ^2.1.0
  objectbox: ^2.4.0
  objectbox_flutter_libs: ^2.4.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  sqflite: ^2.3.0
  flutter_markdown: ^0.6.18
  video_player: ^2.8.1
  chewie: ^1.7.1
  youtube_player_flutter: ^9.1.0
  flutter_inappwebview: ^6.0.0
  pdf: ^3.10.4
  uuid: ^4.2.1
  path: ^1.8.3
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6  
  objectbox_generator: ^2.4.0
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  flutter_tex: ^4.0.3
  animated_text_kit: ^4.2.2
  speech_to_text: ^7.3.0
  flutter_tts: ^3.8.3
  permission_handler: ^11.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/databases/
    - assets/data/
    - assets/ai/
    - assets/images/